global:
  name: Hyperledger DLT Landscape
  short_name: HyperledgerDLTLandscape
  repo: hyperledger-dlt-landscape/hyperledger-dlt-landscape
  website: https://l2.hyperledger.org
  short_domain: l2.hyperledger.org
  company_url: https://hyperledger.org
  email: info@hyperledger.org
  self: https://www.crunchbase.com/organization/hyperledger-2
  membership: Hyperledger Members
  meta:
    title: Hyperledger DLT Landscape
    description:
    twitter: '@hyperledger'
    extra: >
      <meta property="og:image" content="https://landscape.cncf.io/images/social.jpg" />
      <meta property="og:image:width" content="1800" />
      <meta property="og:image:height" content="945" />
      <meta property="og:locale" content="en_US" />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="Hyperledger DLT Landscape" />
      <meta property="og:description" content="A living market landscape with a technology foundation, created by and for the DLT community" />

      <meta property="og:url" content="https://dltlandscape.org/" />
      <meta property="og:site_name" content="Landscape" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Landscape" />
      <meta name="twitter:description" content="The Landscape organizes all cloud native open source projects and proprietary products into categories,
      providing an overview of the current ecosystem" />
      <meta name="twitter:image" content="https://landscape.cncf.io/images/social.jpg" />
      <meta name="twitter:image:width" content="1800" />
      <meta name="twitter:image:height" content="945" />
      <script>document.addEventListener('DOMContentLoaded', function() {
        const options = JSON.parse(document.querySelector('[data-name=project]').getAttribute('data-options'));
        const newOptions = options.filter( (x) => ["company", "project", "member", false].indexOf(x.id) === -1);
        document.querySelector('[data-name=project]').setAttribute('data-options', JSON.stringify(newOptions));
      });</script>

  flags:
    gray_large_items: true
    companies: false
    hide_license_for_categories:
      - Hyperledger Members
  hide_best_practices: true
twitter:
  search: dltlandscape.org
  url: https://dltlandscape.org
  text: DLT Landscape
relation:
  label: Hyperledger Relation
  url: hyperledger
  values:
    - id: hosted
      label: Projects
      children:
        - id: graduated
          label: Graduated Hyperledger Projects
          prefix: Hyperledger
          tag: Graduated
          color: '#7CC142'
          big_picture_order: 1
          big_picture_label: Graduated
          big_picture_color: rgb(124,193,66)
          x4: true
        - id: incubating
          label: Incubating Hyperledger Projects
          prefix: Hyperledger
          tag: Incubating
          color: '#7CC142'
          big_picture_order: 2
          big_picture_label: Incubating
          big_picture_color: rgb(124,193,66)
          x4: true
    - id: hyperledger-member-services
      label: Hyperledger Member Services
      big_picture_label: Member Services
      big_picture_color: rgb(43,137,201)
      tag: Hyperledger Member Services
    - id: hyperledger-member-products
      label: Hyperledger Member Products/Projects
      big_picture_label: Member Products
      big_picture_color: rgb(43,137,201)
      tag: Hyperledger Member
    - id: non-hyperledger-member-services
      label: Non-Hyperledger Member Services
      big_picture_label: Other Services
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member
    - id: non-hyperledger-member-products
      label: Non-Hyperledger Member Products/Projects
      big_picture_label: Other Products
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member
    - id: organization
      tag: Organization
      label: Standards Organization
      color: '#00cbff'
      big_picture_label: Organization
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: network
      tag: Network
      label: Network
      color: '#00cbff'
      big_picture_label: Network
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: company
      tag: Company
      label: Company
      big_picture_label: Company
      big_picture_color: rgb(24,54,114)
      color: rgb(24,54,114)
    - id: project
      tag: Project
      label: Project
      big_picture_label: Project
      big_picture_color: rgb(0,0,0)
      color: '#000000'
    - id: member
      tag: Member
      label: Member
      big_picture_label: Member
      big_picture_color: rgb(24,54,114)
    - id: false
      tag: Other
      label: Other
      big_picture_label: Other
      big_picture_color: rgb(0,0,0)
      color: '#000000'
membership:
  Premier:
    name: Hyperledger
    label: Member
    funding: Premier
    is_large: true
  General:
    name: Hyperledger
    label: Member
    funding: General
  Associate:
    name: Hyperledger
    label: Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Hyperledger DLT Landscape</h1> The Hyperledger DLT landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) is
    dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://www.hyperledger.org/event/hyperledger-global-forum-2022-dublin-ireland
    image: /images/HGF2022.jpg
    title: Hyperledger Global Forum | 12-14 Sep 2022
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Hyperledger DLT Landscape
    fullscreen_header: See the interactive landscape at dltlandscape.org
    elements:
      - type: VerticalCategory
        category: Platforms
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 0
        color: rgb(153,153,0)
        is_large: true
      - type: HorizontalCategory
        category: Multiparty Applications
        rows: 4
        width: 900
        height: 180
        top: 0
        left: 200
        color: rgb(0,181,226)
        is_large: true
      - type: HorizontalCategory
        category: Application Tooling/Integrations
        rows: 6
        width: 900
        height: 280
        top: 200
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Smart Contracts/Tokenization
        rows: 6
        width: 900
        height: 280
        top: 500
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Interoperability
        rows: 4
        width: 900
        height: 180
        top: 800
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Technology Intersections
        rows: 6
        width: 900
        height: 280
        top: 1000
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 8
        width: 900
        height: 320
        top: 1300
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Computing Infrastructure
        rows: 4
        width: 900
        height: 180
        top: 1640
        left: 200
        color: rgb(160,160,160)
        fit_width: false
        is_large: true
      - type: VerticalCategory
        category: Standards
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 1125
        color: rgb(218,165,32)
        is_large: true
      - type: VerticalCategory
        category: Services
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 1320
        color: rgb(204,0,102)
        is_large: true
      - type: LandscapeInfo
        width: 430
        height: 280
        top: 1540
        left: 1125
        children:
          - type: text
            text: |
               This is a living segmentation of the evolving blockchain, and distributed ledger technology (DLT) space, more broadly. Its creation was inspired by the growing complexity of this emerging market, and in particular, all the innovation happening outside the core DLT development area.

               This landscape both reflects and deciphers the complexity of today's vendor landscape. It includes all the Hyperledger Foundation projects - graduated and incubating - and places them in the broader market context.
            top: 80
            left: 130
            right: 20
            font_size: 11
          - type: image
            image: qr.svg
            top: 80
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: dltlandscape.org
            top: 195
            left: 24
            font_size: 16
          - type: image
            image: logo.svg
            width: 120
            left: 20
            top: 20
            title: Landscape Logo
  third:
    tab_index: 1
    url: projects
    name: Projects
    title: Hyperledger Projects
    fullscreen_header: See the interactive landscape at l.hyperledger.org
    elements:
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 6
        width: 970
        height: 200
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Libraries
        rows: 6
        width: 970
        height: 200
        top: 210
        left: 0
        color: rgb(7,136,62)
        fit_width: true
      - type: HorizontalCategory
        category: Tools
        rows: 8
        width: 970
        height: 300
        top: 420
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Domain Specific
        rows: 6
        width: 640
        height: 200
        top: 720
        left: 0
        color: rgb(87,43,10)
        fit_width: true
    category: Hyperledger Projects
  fourth:
    tab_index: 2
    url: members
    name: Members
    title: Hyperledger Members
    fullscreen_header: Become an Hyperledger member at https://www.hyperledger.org/about/join
    elements:
      - type: HorizontalCategory
        category: Premier
        width: 900
        height: 180
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: General
        width: 900
        height: 600
        top: 175
        left: 0
        color: '#d4af37'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Associate
        cols: 30
        width: 1200
        height: 370
        top: 775
        left: 0
        color: '#C0C0C0'
        fit_width: true
        is_large: true
    category: Hyperledger Members
  fifth:
    tab_index: 3
    url: providers
    name: CSPs
    title: Hyperledger Certified Service Providers
    fullscreen_header: Hyperledger Certified Service Providers
    elements:
      - type: HorizontalCategory
        category: Hyperledger Fabric CSPs
        rows: 3
        width: 725
        height: 460
        top: 0
        left: 0
        color: rgb(19,105,73)
        fit_width: true
    category: Hyperledger Certified Service Providers
  sixth:
    tab_index: 4
    url: training
    name: Training Partners
    title: Hyperledger Training Partners
    fullscreen_header: Hyperledger Training Partners
    elements:
      - type: HorizontalCategory
        category: Hyperledger Training Partners
        rows: 4
        width: 740
        height: 460
        top: 0
        left: 0
        color: rgb(126,115,14)
        fit_width: true
    category: Hyperledger Training Partners
test:
  header: Hyperledger DLT Landscape
  section: Project
  logo: google.svg
