global:
  name: DLT Landscape
  short_name: DLTLandscape
  repo: dltlandscape/dlt-landscape
  website: https://dltlandscape.org
  short_domain: https://dltlandscape.org
  company_url: https://dltlandscape.org
  email: dltlandscape@blockchaintp.com
  membership: Hyperledger Members
  meta:
    title: DLT Landscape
    description: A living market landscape with a technology foundation, created by and for the DLT community
    twitter: '@dltlandscape'
  flags:
    gray_large_items: true
    companies: false
    hide_license_for_categories:
      - Hyperledger Members
  hide_best_practices: true
twitter:
  search: dltlandscape.org
  url: https://dltlandscape.org
  text: DLT Landscape
relation:
  label: Hyperledger Relation
  url: hyperledger
  values:
    - id: hosted
      label: Projects
      children:
        - id: graduated
          label: Graduated Hyperledger Projects
          prefix: Hyperledger
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating Hyperledger Projects
          prefix: Hyperledger
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: Incubating
          big_picture_color: rgb(83, 113, 189)
    - id: hyperledger-member-services
      label: Hyperledger Member Services
      big_picture_label: Hyperledger Services
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member Services
    - id: hyperledger-member-products
      label: Hyperledger Project Member Products/Projects
      big_picture_label: Hyperledger Products
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member
    - id: non-hyperledger-member-services
      label: Non Hyperledger Project Member Services
      big_picture_label: Other Services
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member
    - id: non-hyperledger-member-products
      label: Non Hyperledger Project Member Products/Projects
      big_picture_label: Other Products
      big_picture_color: rgb(24,54,114)
      tag: Hyperledger Member
    - id: organization
      tag: Organization
      label: Standards Organization
      color: '#00cbff'
      big_picture_label: Organization
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: network
      tag: Network
      label: Network
      color: '#00cbff'
      big_picture_label: Network
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: company
      tag: Company
      label: Company
      big_picture_label: Company
      big_picture_color: rgb(24,54,114)
      color: rgb(24,54,114)
    - id: project
      tag: Project(remove)
      label: Project(remove)
      big_picture_label: Project
      big_picture_color: rgb(0,0,0)
      color: '#000000'
    - id: member
      tag: Member
      label: Member
      big_picture_label: Member
      big_picture_color: rgb(24,54,114)
    - id: false
      tag: Other(remove)
      label: Other(remove)
      big_picture_label: Other
      big_picture_color: rgb(0,0,0)
      color: '#000000'
membership:
  Premier:
    name: Hyperledger
    label: Member
    funding: Premier
    is_large: true
  General:
    name: Hyperledger
    label: Member
    funding: General
  Associate:
    name: Hyperledger
    label: Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>DLT Landscape</h1> The DLT landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) is
    dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://www.hyperledger.org/event/hyperledger-global-forum-2022-dublin-ireland
    image: /images/HGF2022.jpg
    title: Hyperledger Global Forum | 12-14 Sep 2022
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: DLT Landscape
    fullscreen_header: See the interactive landscape at dltlandscape.org
    elements:
      - type: VerticalCategory
        category: Platforms
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 0
        color: rgb(153,153,0)
        is_large: true
      - type: HorizontalCategory
        category: Multiparty Applications
        rows: 4
        width: 900
        height: 180
        top: 0
        left: 200
        color: rgb(0,181,226)
        is_large: true
      - type: HorizontalCategory
        category: Application Tooling/Integrations
        rows: 4
        width: 900
        height: 180
        top: 200
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Smart Contracts/Tokenization
        rows: 6
        width: 900
        height: 240
        top: 400
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Interoperability
        rows: 4
        width: 900
        height: 180
        top: 680
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Technology Intersections
        rows: 4
        width: 900
        height: 180
        top: 900
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 6
        width: 900
        height: 220
        top: 1100
        left: 200
        color: rgb(0,128,255)
        fit_width: false
        is_large: true
      - type: HorizontalCategory
        category: Computing Infrastructure
        rows: 4
        width: 900
        height: 180
        top: 1340
        left: 200
        color: rgb(160,160,160)
        fit_width: false
        is_large: true
      - type: VerticalCategory
        category: Standards
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 1125
        color: rgb(218,165,32)
        is_large: true
      - type: VerticalCategory
        category: Services
        cols: 4
        width: 175
        height: 1520
        top: 0
        left: 1320
        color: rgb(204,0,102)
        is_large: true
      - type: LandscapeInfo
        width: 430
        height: 280
        top: 1540
        left: 0
        children:
          - type: text
            text: |
              Welcome to a living segmentation of the evolving DLT market! DLT Landscape is a
              business stack with a technology foundation. BTP has created the DLT Landscape
              for the whole blockchain/DLT community to benefit from and contribute to. The
              DLT Landscape is open source, curated and hosted by BTP, but independent of the company.
            top: 80
            left: 130
            right: 20
            font_size: 11
          - type: image
            image: qr.svg
            top: 80
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: dltlandscape.org
            top: 195
            left: 24
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 120
            left: 20
            top: 20
            title: Landscape Logo
  third:
    tab_index: 1
    url: projects
    name: Projects
    title: Hyperledger Projects
    fullscreen_header: See the interactive landscape at l.hyperledger.org
    elements:
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 4
        width: 470
        height: 160
        top: 0
        left: 0
        color: rgb(4,81,49)
        fit_width: true
      - type: HorizontalCategory
        category: Libraries
        rows: 4
        width: 470
        height: 160
        top: 170
        left: 0
        color: rgb(7,136,62)
        fit_width: true
      - type: HorizontalCategory
        category: Tools
        rows: 4
        width: 470
        height: 160
        top: 340
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Domain Specific
        rows: 4
        width: 240
        height: 160
        top: 510
        left: 0
        color: rgb(87,43,10)
        fit_width: true
    category: Hyperledger Projects
  fourth:
    tab_index: 2
    url: members
    name: Members
    title: Hyperledger Members
    fullscreen_header: Become an Hyperledger member at https://www.hyperledger.org/about/join
    elements:
      - type: HorizontalCategory
        category: Premier
        width: 900
        height: 180
        top: 0
        left: 0
        color: '#e5e4e2'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: General
        width: 900
        height: 600
        top: 175
        left: 0
        color: '#d4af37'
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Associate
        cols: 30
        width: 1200
        height: 370
        top: 775
        left: 0
        color: '#C0C0C0'
        fit_width: true
        is_large: true
    category: Hyperledger Members
  fifth:
    tab_index: 3
    url: providers
    name: CSPs
    title: Hyperledger Certified Service Providers
    fullscreen_header: Hyperledger Certified Service Providers
    elements:
      - type: HorizontalCategory
        category: Hyperledger Fabric CSPs
        rows: 3
        width: 725
        height: 460
        top: 0
        left: 0
        color: rgb(19,105,73)
        fit_width: true
    category: Hyperledger Certified Service Providers
  sixth:
    tab_index: 4
    url: training
    name: Training Partners
    title: Hyperledger Training Partners
    fullscreen_header: Hyperledger Training Partners
    elements:
      - type: HorizontalCategory
        category: Hyperledger Training Partners
        rows: 4
        width: 740
        height: 460
        top: 0
        left: 0
        color: rgb(126,115,14)
        fit_width: true
    category: Hyperledger Training Partners
test:
  header: DLT Landscape
  section: Project
  logo: google.svg
