global:
  name: DLT Landscape
  short_name: DLTLandscape
  repo: dltlandscape/dlt-landscape
  website: https://dltlandscape.org
  short_domain: https://dltlandscape.org
  company_url: https://dltlandscape.org
  email: dltlandscape@blockchaintp.com
  # self: https://www.crunchbase.com/organization/
  # slack_channel:
  membership: Members
  meta:
    title: DLT Landscape
    description: A living market landscape with a technology foundation, created by and for the DLT community
    # fb_admin: username
    twitter: '@dltlandscape'
    # google_site_verification:
    # ms_validate:
  flags:
    companies: false
    hide_license_for_categories:
      - Members
  hide_best_practices: true
twitter:
  search: dltlandscape.org
  url: https://dltlandscape.org
  text: DLT Landscape
relation:
  label: Group
  url: groups
  values:
    - id: groups
      label: Groups
      children:
        - id: company
          tag: Company
          label: Company
          color: '#00cbff'
          big_picture_label: Company
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
        - id: project
          tag: Project
          label: Project
          color: '#00cbff'
          big_picture_label: Project
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
        - id: network
          tag: Network
          label: Network
          color: '#00cbff'
          big_picture_label: Network
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
        - id: organization
          tag: Organization
          label: Organization
          color: '#00cbff'
          big_picture_label: Organization
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
    - id: false
      label: NA
      url: 'no'
membership:
  Platinum:
    name: Platinum
    label: Platinum Member
    funding: Platinum
    is_large: true
  Gold:
    name: Gold
    label: Gold Member
    funding: Gold
    is_large: true
  Silver:
    name: Silver
    label: Silver Member
    funding: Silver
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>DLT Landscape</h1> The DLT landscape (<a target="_blank" href="images/landscape.png">png</a>, <a
    target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF
    landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://eblockchainconvention.com/
    image: /images/EBC_June_2022.jpeg
    title: European Blockchain Convention | 26-28 June 2022
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: DLT Landscape
    fullscreen_header: See the interactive landscape at dltlandscape.org
    elements:
      - type: VerticalCategory
        category: Platforms
        cols: 4
        width: 175
        height: 1360
        top: 0
        left: 0
        color: rgb(153,153,0)
      - type: HorizontalCategory
        category: Multiparty Applications
        rows: 4
        width: 900
        height: 180
        top: 0
        left: 200
        color: rgb(0,181,226)
      - type: HorizontalCategory
        category: Application Tooling/Integrations
        rows: 4
        width: 900
        height: 180
        top: 200
        left: 200
        color: rgb(0,128,255)
        fit_width: false
      - type: HorizontalCategory
        category: Smart Contracts/Tokenization
        rows: 4
        width: 900
        height: 180
        top: 400
        left: 200
        color: rgb(0,128,255)
        fit_width: false
      - type: HorizontalCategory
        category: Interoperability
        rows: 4
        width: 900
        height: 180
        top: 600
        left: 200
        color: rgb(0,128,255)
        fit_width: false
      - type: HorizontalCategory
        category: Technology Intersections
        rows: 4
        width: 900
        height: 180
        top: 800
        left: 200
        color: rgb(0,128,255)
        fit_width: false
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 4
        width: 900
        height: 180
        top: 1000
        left: 200
        color: rgb(0,128,255)
        fit_width: false
      - type: HorizontalCategory
        category: Computing Infrastructure
        rows: 4
        width: 900
        height: 180
        top: 1200
        left: 200
        color: rgb(160,160,160)
        fit_width: false
      - type: VerticalCategory
        category: Standards
        cols: 4
        width: 175
        height: 1360
        top: 0
        left: 1125
        color: rgb(218,165,32)
      - type: VerticalCategory
        category: Services
        cols: 4
        width: 175
        height: 1360
        top: 0
        left: 1320
        color: rgb(204,0,102)
      - type: LandscapeInfo
        width: 430
        height: 280
        top: 1400
        left: 0
        children:
          - type: text
            text: |
              Welcome to a living segmentation of the evolving DLT market! DLT Landscape is a
              business stack with a technology foundation. BTP has created the DLT Landscape
              for the whole blockchain/DLT community to benefit from and contribute to. The
              DLT Landscape is open source, curated and hosted by BTP, but independent of the company.
            top: 80
            left: 130
            right: 20
            font_size: 11
          - type: image
            image: qr.svg
            top: 80
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: dltlandscape.org
            top: 195
            left: 24
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 120
            left: 20
            top: 20
            title: Landscape Logo
test:
  header: DLT Landscape
  section: Project
  logo: google.svg
